### ISSUE TITLE
'FrozenDict' object has no attribute 'shift_factor'

### ISSUE THREAD

**Issue by miggosec** [chflame163/ComfyUI_OmniGen_Wrapper#3]
# ComfyUI Error Report
## Error Details
- **Node Type:** dzOmniGenWrapper
- **Exception Type:** AttributeError
- **Exception Message:** 'FrozenDict' object has no attribute 'shift_factor'
## Stack Trace
```
  File "E:\Comfyui_mi\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\Comfyui_mi\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 130, in run_omnigen
    output = self.model.pipe(
             ^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 247, in __call__
    img = self.vae_encode(img.to(self.device, dtype=torch.bfloat16), dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 115, in vae_encode
    if self.vae.config.shift_factor is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** E:\Comfyui_mi\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2080 Ti : native
  - **Type:** cuda
  - **VRAM Total:** 23621992448
  - **VRAM Free:** 9426860544
  - **Torch VRAM Total:** 10468982784
  - **Torch VRAM Free:** 267024896

## Logs
```
2024-11-07 19:23:23,450 - root - INFO - Total VRAM 22528 MB, total RAM 32674 MB
2024-11-07 19:23:23,450 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-07 19:23:25,629 - root - INFO - xformers version: 0.0.28.post1
2024-11-07 19:23:25,641 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 19:23:25,641 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
2024-11-07 19:23:26,060 - root - INFO - Using xformers cross attention
2024-11-07 19:23:27,387 - root - INFO - [Prompt Server] web root: E:\Comfyui_mi\ComfyUI\web
2024-11-07 19:23:33,728 - numexpr.utils - INFO - NumExpr defaulting to 16 threads.
2024-11-07 19:23:37,211 - comfy-deploy - INFO - CD_BYPASS_UPLOAD False
2024-11-07 19:23:46,886 - root - INFO - Model successfully loaded!
2024-11-07 19:23:47,245 - root - INFO - Total VRAM 22528 MB, total RAM 32674 MB
2024-11-07 19:23:47,245 - root - INFO - pytorch version: 2.4.1+cu124
2024-11-07 19:23:47,245 - root - INFO - xformers version: 0.0.28.post1
2024-11-07 19:23:47,245 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 19:23:47,245 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
2024-11-07 19:23:50,903 - root - INFO - --------------
2024-11-07 19:23:50,903 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-07 19:23:50,916 - root - INFO - ChatGPT.available True
2024-11-07 19:23:50,917 - root - INFO - edit_mask.available True
2024-11-07 19:23:50,925 - root - INFO - LaMaInpainting.available True
2024-11-07 19:23:51,099 - root - INFO - ClipInterrogator.available True
2024-11-07 19:23:51,493 - root - INFO - PromptGenerate.available True
2024-11-07 19:23:51,493 - root - INFO - ChinesePrompt.available True
2024-11-07 19:23:51,493 - root - INFO - RembgNode_.available True
2024-11-07 19:23:52,237 - root - INFO - TripoSR.available
2024-11-07 19:23:52,238 - root - INFO - MiniCPMNode.available
2024-11-07 19:23:52,321 - root - INFO - Scenedetect.available
2024-11-07 19:23:52,450 - root - INFO - FishSpeech.available
2024-11-07 19:23:52,467 - root - INFO - SenseVoice.available
2024-11-07 19:23:52,534 - root - INFO - Whisper.available False
2024-11-07 19:23:52,547 - root - INFO - FalVideo.available
2024-11-07 19:23:52,547 - root - INFO - [93m -------------- [0m
2024-11-07 19:23:57,387 - datasets - INFO - PyTorch version 2.4.1+cu124 available.
2024-11-07 19:23:57,392 - datasets - INFO - TensorFlow version 2.17.0 available.
2024-11-07 19:24:09,369 - root - INFO - 
Import times for custom nodes:
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-NodeAligner
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\quick-connections
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-AIDSSJ
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Molmo
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-FluxExt-MZ
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-11-07 19:24:09,369 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_Cutoff
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-YOLO
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\cg-use-everywhere
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\cg-image-picker
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_SLK_joy_caption_two
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyLiterals
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-animatediff
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-portrait-master
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Image-Saver
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-BrushNet
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfy-image-saver
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Marigold
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-various
2024-11-07 19:24:09,370 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyMath
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\OneButtonPrompt
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\Steerable-Motion
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\Comfyui_Comfly
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\x-flux-comfyui
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui_segment_anything
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\rgthree-comfy
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-11-07 19:24:09,371 - root - INFO -    0.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-MingNodes
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-dream-project
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfy_mtb
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_toyxyz_test_nodes
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-07 19:24:09,371 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-11-07 19:24:09,372 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-11-07 19:24:09,372 - root - INFO -    0.1 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-07 19:24:09,372 - root - INFO -    0.2 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-deploy
2024-11-07 19:24:09,372 - root - INFO -    0.2 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-07 19:24:09,372 - root - INFO -    0.2 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\eden_comfy_pipelines
2024-11-07 19:24:09,372 - root - INFO -    0.3 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-11-07 19:24:09,372 - root - INFO -    0.6 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Anyline
2024-11-07 19:24:09,372 - root - INFO -    0.8 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-07 19:24:09,372 - root - INFO -    0.8 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-DDColor
2024-11-07 19:24:09,372 - root - INFO -    0.8 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-07 19:24:09,372 - root - INFO -    1.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\NodeGPT
2024-11-07 19:24:09,372 - root - INFO -    1.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-InstantID
2024-11-07 19:24:09,372 - root - INFO -    1.5 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-art-venture
2024-11-07 19:24:09,372 - root - INFO -    2.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-07 19:24:09,372 - root - INFO -    2.8 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\SeargeSDXL
2024-11-07 19:24:09,372 - root - INFO -    2.9 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
2024-11-07 19:24:09,372 - root - INFO -    3.3 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-11-07 19:24:09,372 - root - INFO -    5.0 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
2024-11-07 19:24:09,372 - root - INFO -    6.8 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-07 19:24:09,372 - root - INFO -    8.7 seconds: E:\Comfyui_mi\ComfyUI\custom_nodes\comfyui-faceaging
2024-11-07 19:24:09,372 - root - INFO - 
2024-11-07 19:24:09,396 - root - INFO - Starting server

2024-11-07 19:24:09,397 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-07 19:24:25,487 - root - INFO - got prompt
2024-11-07 19:25:35,300 - root - ERROR - !!! Exception during processing !!! 'FrozenDict' object has no attribute 'shift_factor'
2024-11-07 19:25:35,371 - root - ERROR - Traceback (most recent call last):
  File "E:\Comfyui_mi\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Comfyui_mi\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 130, in run_omnigen
    output = self.model.pipe(
             ^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 247, in __call__
    img = self.vae_encode(img.to(self.device, dtype=torch.bfloat16), dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui_mi\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 115, in vae_encode
    if self.vae.config.shift_factor is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FrozenDict' object has no attribute 'shift_factor'

2024-11-07 19:25:35,378 - root - INFO - Prompt executed in 69.87 seconds
2024-11-07 19:25:37,636 - comfy-deploy - INFO - No pending upload
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":5,"last_link_id":4,"nodes":[{"id":5,"type":"PreviewImage","pos":{"0":808,"1":-302},"size":{"0":210,"1":26},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":4,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":1,"type":"dzOmniGenWrapper","pos":{"0":343,"1":-315},"size":{"0":407.46929931640625,"1":391.47052001953125},"flags":{},"order":2,"mode":0,"inputs":[{"name":"image_1","type":"IMAGE","link":1,"shape":7,"label":"image_1"},{"name":"image_2","type":"IMAGE","link":3,"shape":7,"label":"image_2"},{"name":"image_3","type":"IMAGE","link":null,"shape":7,"label":"image_3"}],"outputs":[{"name":"image","type":"IMAGE","links":[4],"slot_index":0,"label":"image"}],"properties":{"Node name for S&R":"dzOmniGenWrapper"},"widgets_values":["default","{image_2},{image_1}",512,512,2.5,1.6,25,true,false,1111502973895286,"randomize",false]},{"id":2,"type":"LoadImage","pos":{"0":-115,"1":-472},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["e45172a23f4e1457895397b158aa854.jpg","image"]},{"id":4,"type":"LoadImage","pos":{"0":-110,"1":-84},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[3],"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["693fced2bba.jpg","image"]}],"links":[[1,2,0,1,0,"IMAGE"],[3,4,0,1,1,"IMAGE"],[4,1,0,5,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7247295000000004,"offset":[961.716878933834,798.6877976213981]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by miggosec** [comment]
这个是啥问题，模型是下好了的，说vae模型没这个shift_factor

**Comment by heiyu8** [comment]
solve it by install latest diffusers: pip install -U diffusers
